### ISSUE TITLE
Re-fork repositories to avoid confusion

### ISSUE THREAD

**Issue by allemangD** [DCBIA-OrthoLab/SlicerConda#1]
One of the nitpick issues mentioned in https://github.com/Slicer/ExtensionsIndex/pull/2006#pullrequestreview-1908976539

To avoid confusion, delete the upstream project https://github.com/GaelleLeroux/SlicerConda and re-fork the one hosted in this DCBIA-OrthoLab organization.

This will make the DCBIA-OrthoLab organization's repository the upstream and unambiguous source of truth moving forward.

**Comment by GaelleLeroux** [comment]
Did it !
